cName = "8088 Based Microprocessor"
cFreq = 32
cFreqS = "32"
cFreqUnit = "MHz"
mName = "BASIC MOTHERBOARD"
mMem = 2048
mMemS = "2048 KB"
spCpus = "8088"
onboardGPU = True
gName = "Basic Video Processor"
gSpeedS = "1MHz"
gFreq = 1
gMems = "0.9MB"
gVram = 0.9
gps = 1
gvs = 0
grop = 1
hddnameS = "GENERIC IDE DISK"
hddspace = 4000
hddspaceS = "4MB"
modemname = "14.4kbps Modem"
modemspeed = 14.4
modemspeeds = "14.4kbps"
dialupadp = "Basic Dial-Up Adapter"
laptopName = "Basic Laptop"
battery = 100
intscreen = "MATRIX SCREEN"
maxlight = 25
minlight = 5
laptophardware = True
asdawd2k3a403 = "386"
kajsaed = True
odasfsdfds3 = True
ioaoooss = True
saiop = True